# 服务器端口篇配置
server:
  port: 8081

# 开发环境设置
logging:
  level:
    com.demo.demo.sys.mapper: debug  # debug 层级下会显示sql执行过程

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://1***/***?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    username: ***
    password: ***